name: Deploy
on: {push: {branches: [main]}}
jobs:
  railway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bervProject/railway-deploy@v0.1.2
        if: ${{ secrets.RAILWAY_TOKEN != '' && secrets.RAILWAY_SERVICE_ID != '' }}
        with: {token: '${{ secrets.RAILWAY_TOKEN }}', service: '${{ secrets.RAILWAY_SERVICE_ID }}'}
